name: Test
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    name: Node ${{ matrix.node }} on Ubuntu
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [16, 18, 20]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install npm dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        uses: BerniWittmann/background-server-action@v1
        with:
          command: npm test
          start: npm start -- --silent
